services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    image: mawi-backend:prod
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_AGROMO=${DB_AGROMO}
      - DB_BIOMO=${DB_BIOMO}
      - DB_ROBO=${DB_ROBO}
      - DB_BACK=${DB_BACK}
      - DB_SSL=${DB_SSL}
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}
    expose:
      - "3000"       # only expose internally, don't bind 80/443
    restart: unless-stopped
