FROM grafana/grafana:11.2.2

# Copy Grafana configuration files into the image
COPY grafana/grafana.ini /etc/grafana/grafana.ini
COPY grafana/*.json /etc/grafana/provisioning/dashboards/

# Expose Grafana port
EXPOSE 3000

# Use the default grafana entrypoint
