services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    image: mawi-backend:latest
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_AGROMO=${DB_AGROMO}
      - DB_BIOMO=${DB_BIOMO}
      - DB_ROBO=${DB_ROBO}
      - DB_BACK=${DB_BACK}
      - DB_SSL=${DB_SSL}
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4318/v1/metrics
    ports:
      - "3000:3000"
    volumes:
      - ../src:/usr/src/app/src
    restart: unless-stopped
  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../caddy/Caddyfile.local:/etc/caddy/Caddyfile
      - ../caddy/ssl:/etc/caddy/ssl
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    restart: unless-stopped
  tempo:
    image: grafana/tempo:latest
    ports:
      - "4318:4318"  # OTLP traces
      - "3200:3200"  # Tempo API
    volumes:
      - ./observability/tempo-config.yaml:/etc/tempo.yaml
    command: ["-config.file=/etc/tempo.yaml"]
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prom.yml
    command: ["--config.file=/etc/prom.yml", "--web.enable-remote-write-receiver"]
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"  # Avoid conflict with API on 3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel.yaml
    command: ["--config=/etc/otel.yaml"]
    ports:
      - "4319:4318"  # Expose collector on 4319 to avoid conflict with Tempo
    depends_on:
      - tempo
      - prometheus
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  grafana_data:
