services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    image: mawi-backend:latest
    environment:
      - PORT=3000
      - OTEL_SERVICE_NAME=mawi-backend
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_AGROMO=${DB_AGROMO}
      - DB_BIOMO=${DB_BIOMO}
      - DB_ROBO=${DB_ROBO}
      - DB_BACK=${DB_BACK}
      - DB_SSL=${DB_SSL}
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4318/v1/metrics
      - PROMETHEUS_URL=http://prometheus:9090
    ports:
      - "3000:3000"
    volumes:
      - ../src:/usr/src/app/src
    restart: unless-stopped
  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../caddy/Caddyfile.local:/etc/caddy/Caddyfile
      - ../caddy/ssl:/etc/caddy/ssl
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--web.enable-remote-write-receiver", "--storage.tsdb.retention.time=30d"]
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"  # Changed from 3001 to avoid port conflict
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_LOG_LEVEL=debug
      - GF_FEATURE_TOGGLES_PROVISIONING=true
      - GF_FEATURE_TOGGLES_KUBERNETESDASHBOARDS=true
    volumes:
      - ./grafana/custom.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otelcol/config.yaml
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4319:4318"  # Expose collector on 4319
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  grafana_data:
  prometheus_data:
