services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    image: mawi-backend:prod
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_AGROMO=${DB_AGROMO}
      - DB_BIOMO=${DB_BIOMO}
      - DB_ROBO=${DB_ROBO}
      - DB_BACK=${DB_BACK}
      - DB_SSL=${DB_SSL}
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4318/v1/metrics
      - PROMETHEUS_URL=http://prometheus:9090
    expose:
      - "3000"       # only expose internally, don't bind 80/443
    depends_on:
      - prometheus
      - otel-collector
    restart: unless-stopped
 
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--web.enable-remote-write-receiver", "--storage.tsdb.retention.time=30d"]
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"  # Changed from 3001 to avoid port conflict
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4319:4318"  # Expose collector on 4319 to avoid conflict with Tempo
    depends_on:
      - prometheus
    restart: unless-stopped