server:
  http_listen_port: 3200

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318